name: Compile with SourceMod

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          # echo "SCRIPTS_PATH=" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=" >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: Sarrus1/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}
          version-file: ./example.sp

      - name: Compile plugins
        run: |
          for file in example.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i include $file
          done
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}
